In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [4]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [5]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [7]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [9]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  120649.75 
Prediction:
 [-157.4425  -185.61145 -185.01326 -198.49052 -143.10315]
10 Cost:  4.49821 
Prediction:
 [149.82013 183.69858 178.8726  197.7714  138.58875]
20 Cost:  3.3907974 
Prediction:
 [150.74814 184.8172  179.9732  198.96922 139.44336]
30 Cost:  3.3878913 
Prediction:
 [150.7493  184.82181 179.97612 198.97176 139.44823]
40 Cost:  3.3849664 
Prediction:
 [150.74763 184.82303 179.97574 198.97064 139.45053]
50 Cost:  3.3820724 
Prediction:
 [150.74599 184.82425 179.97533 198.96954 139.45282]
60 Cost:  3.3791816 
Prediction:
 [150.74434 184.82544 179.97493 198.96843 139.4551 ]
70 Cost:  3.3762918 
Prediction:
 [150.74269 184.82664 179.97453 198.9673  139.45735]
80 Cost:  3.3734193 
Prediction:
 [150.74106 184.82785 179.97414 198.9662  139.45963]
90 Cost:  3.3705277 
Prediction:
 [150.73944 184.82906 179.97375 198.9651  139.46191]
100 Cost:  3.3676713 
Prediction:
 [150.73782 184.83026 179.97336 198.964   139.46417]
110 Cost:  3.3648338 
Prediction:
 [150.73618 184.8

1020 Cost:  3.1357265 
Prediction:
 [150.60931 184.92587 179.94356 198.86798 139.65253]
1030 Cost:  3.133489 
Prediction:
 [150.60814 184.92677 179.94331 198.86699 139.65437]
1040 Cost:  3.1312575 
Prediction:
 [150.60696 184.92767 179.94305 198.86601 139.65623]
1050 Cost:  3.1290486 
Prediction:
 [150.60577 184.92856 179.9428  198.86502 139.65807]
1060 Cost:  3.1268365 
Prediction:
 [150.6046  184.92946 179.94254 198.86404 139.65991]
1070 Cost:  3.1246414 
Prediction:
 [150.60342 184.93034 179.94229 198.86307 139.66174]
1080 Cost:  3.1224387 
Prediction:
 [150.60226 184.93121 179.94202 198.86208 139.66356]
1090 Cost:  3.1202316 
Prediction:
 [150.60109 184.93208 179.94177 198.86108 139.66539]
1100 Cost:  3.1180332 
Prediction:
 [150.59993 184.93297 179.94151 198.86009 139.6672 ]
1110 Cost:  3.1158326 
Prediction:
 [150.59879 184.93384 179.94125 198.85912 139.66904]
1120 Cost:  3.113665 
Prediction:
 [150.59764 184.93471 179.94102 198.85815 139.67085]
1130 Cost:  3.1114898 
Prediction: