In [14]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
# print(x_data, "\nx_data shape:", x_data.shape)
# print(y_data, "\ny_data shape:", y_data.shape)

In [15]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')


In [16]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)


In [17]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], 
                                   feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n", hy_val)

0 Cost: 25492.05 
Prediction:
 [[ 3.0294957 ]
 [ 7.842961  ]
 [ 5.738896  ]
 [ 3.835423  ]
 [ 9.066868  ]
 [ 3.5434995 ]
 [-1.8282123 ]
 [-8.07114   ]
 [ 5.4026914 ]
 [ 0.10525942]
 [ 1.9737325 ]
 [ 2.9045987 ]
 [ 8.458988  ]
 [10.793282  ]
 [-1.4684329 ]
 [ 5.277043  ]
 [14.520981  ]
 [-4.7392917 ]
 [ 7.8022504 ]
 [ 6.1093793 ]
 [-0.7203326 ]
 [ 4.7573743 ]
 [-0.35234404]
 [ 8.906216  ]
 [ 8.587849  ]]
10 Cost: 57.49543 
Prediction:
 [[151.93974]
 [186.82474]
 [182.0887 ]
 [195.90692]
 [145.56006]
 [104.19539]
 [141.96219]
 [ 98.55153]
 [172.69128]
 [155.08487]
 [140.49637]
 [139.49829]
 [190.63925]
 [162.21985]
 [142.98517]
 [186.91354]
 [158.72054]
 [167.83035]
 [181.48215]
 [161.51332]
 [167.89279]
 [172.67883]
 [160.40277]
 [159.01207]
 [194.07468]]
20 Cost: 55.95454 
Prediction:
 [[152.96004 ]
 [188.05608 ]
 [183.29823 ]
 [197.23755 ]
 [146.48944 ]
 [104.90172 ]
 [142.9766  ]
 [ 99.329124]
 [173.85951 ]
 [156.19682 ]
 [141.46153 ]
 [140.45729 ]
 [191.87534 ]
 [163.22864 ]
 [144.0

380 Cost: 45.59822 
Prediction:
 [[152.69533 ]
 [187.87408 ]
 [183.01207 ]
 [197.37262 ]
 [146.01588 ]
 [105.25818 ]
 [143.70435 ]
 [100.740555]
 [174.2671  ]
 [157.57443 ]
 [141.7443  ]
 [140.9676  ]
 [191.12344 ]
 [161.97253 ]
 [144.80737 ]
 [188.40424 ]
 [157.96957 ]
 [170.17923 ]
 [181.84879 ]
 [161.90976 ]
 [169.79218 ]
 [174.10393 ]
 [162.0704  ]
 [158.68349 ]
 [194.92256 ]]
390 Cost: 45.346176 
Prediction:
 [[152.68874 ]
 [187.86876 ]
 [183.00453 ]
 [197.37599 ]
 [146.00296 ]
 [105.266785]
 [143.7233  ]
 [100.77753 ]
 [174.27686 ]
 [157.60922 ]
 [141.75146 ]
 [140.98026 ]
 [191.10385 ]
 [161.93987 ]
 [144.8281  ]
 [188.40965 ]
 [157.92525 ]
 [170.2087  ]
 [181.82787 ]
 [161.89285 ]
 [169.81064 ]
 [174.11006 ]
 [162.0845  ]
 [158.64943 ]
 [194.91121 ]]
400 Cost: 45.09588 
Prediction:
 [[152.68219]
 [187.86346]
 [182.99702]
 [197.37933]
 [145.99005]
 [105.27533]
 [143.7422 ]
 [100.8144 ]
 [174.28654]
 [157.64386]
 [141.7586 ]
 [140.99284]
 [191.08435]
 [161.90733]
 [144.84874]
 [1

610 Cost: 40.22071 
Prediction:
 [[152.55566]
 [187.7522 ]
 [182.84737]
 [197.44797]
 [145.7242 ]
 [105.44173]
 [144.12688]
 [101.56431]
 [174.4752 ]
 [158.33453]
 [141.90341]
 [141.24251]
 [190.69258]
 [161.25235]
 [145.26694]
 [188.51933]
 [156.98834]
 [170.83676]
 [181.39038]
 [161.54094]
 [170.20355]
 [174.23563]
 [162.38603]
 [157.93782]
 [194.66861]]
620 Cost: 40.00571 
Prediction:
 [[152.55013 ]
 [187.7469  ]
 [182.84058 ]
 [197.45117 ]
 [145.71176 ]
 [105.449066]
 [144.1446  ]
 [101.59889 ]
 [174.4835  ]
 [158.36572 ]
 [141.91002 ]
 [141.25372 ]
 [190.67474 ]
 [161.22246 ]
 [145.28613 ]
 [188.52394 ]
 [156.94745 ]
 [170.86441 ]
 [181.37149 ]
 [161.5258  ]
 [170.2208  ]
 [174.2409  ]
 [162.39932 ]
 [157.90709 ]
 [194.65793 ]]
630 Cost: 39.792137 
Prediction:
 [[152.54463]
 [187.74161]
 [182.83382]
 [197.45435]
 [145.69937]
 [105.45634]
 [144.16231]
 [101.63337]
 [174.49174]
 [158.39676]
 [141.91664]
 [141.26485]
 [190.65695]
 [161.19267]
 [145.30527]
 [188.52849]
 [156.90668]
 [

1010 Cost: 32.668053 
Prediction:
 [[152.36555]
 [187.54227]
 [182.59865]
 [197.57022]
 [145.24434]
 [105.69695]
 [144.79813]
 [102.87184]
 [174.7638 ]
 [159.4727 ]
 [142.15178]
 [141.64645]
 [190.03235]
 [160.1413 ]
 [145.98758]
 [188.67963]
 [155.45811]
 [171.8866 ]
 [180.69554]
 [160.9887 ]
 [170.85338]
 [174.42174]
 [162.89183]
 [156.81084]
 [194.2623 ]]
1020 Cost: 32.504204 
Prediction:
 [[152.36156 ]
 [187.53708 ]
 [182.593   ]
 [197.57317 ]
 [145.23279 ]
 [105.702415]
 [144.81395 ]
 [102.90263 ]
 [174.76994 ]
 [159.49846 ]
 [142.15758 ]
 [141.65547 ]
 [190.01718 ]
 [160.11563 ]
 [146.00443 ]
 [188.68307 ]
 [155.4225  ]
 [171.9114  ]
 [180.67967 ]
 [160.97621 ]
 [170.86864 ]
 [174.42577 ]
 [162.90381 ]
 [156.78517 ]
 [194.25269 ]]
1030 Cost: 32.341423 
Prediction:
 [[152.35759]
 [187.53189]
 [182.58736]
 [197.57605]
 [145.22125]
 [105.70783]
 [144.82971]
 [102.93333]
 [174.77605]
 [159.52408]
 [142.16333]
 [141.66443]
 [190.00204]
 [160.09004]
 [146.02118]
 [188.68648]
 [155.3870

 [193.91414]]
1400 Cost: 27.022703 
Prediction:
 [[152.2336 ]
 [187.34224]
 [182.39583]
 [197.67934]
 [144.80919]
 [105.88069]
 [145.38252]
 [104.00904]
 [174.97061]
 [160.39027]
 [142.36339]
 [141.96344]
 [189.48318]
 [159.20888]
 [146.60501]
 [188.79535]
 [154.15604]
 [172.80624]
 [180.12582]
 [160.54346]
 [171.41522]
 [174.55934]
 [163.33679]
 [155.89058]
 [193.90544]]
1410 Cost: 26.896267 
Prediction:
 [[152.23082 ]
 [187.33719 ]
 [182.39108 ]
 [197.68202 ]
 [144.79845 ]
 [105.88469 ]
 [145.39667 ]
 [104.036575]
 [174.97508 ]
 [160.4116  ]
 [142.36847 ]
 [141.97069 ]
 [189.4702  ]
 [159.18674 ]
 [146.61983 ]
 [188.79787 ]
 [154.1249  ]
 [172.82858 ]
 [180.11249 ]
 [160.53311 ]
 [171.42877 ]
 [174.5624  ]
 [163.34763 ]
 [155.86905 ]
 [193.89677 ]]
1420 Cost: 26.77064 
Prediction:
 [[152.22806]
 [187.33215]
 [182.38637]
 [197.68471]
 [144.78772]
 [105.88865]
 [145.41078]
 [104.06402]
 [174.97952]
 [160.43283]
 [142.37352]
 [141.97792]
 [189.45728]
 [159.16467]
 [146.63461]
 [188.8003

1830 Cost: 22.266088 
Prediction:
 [[152.13657 ]
 [187.12926 ]
 [182.21002 ]
 [197.78903 ]
 [144.3653  ]
 [106.023834]
 [145.956   ]
 [105.12397 ]
 [175.13062 ]
 [161.21983 ]
 [142.56657 ]
 [142.24098 ]
 [188.96906 ]
 [158.32756 ]
 [147.2013  ]
 [188.8859  ]
 [152.90741 ]
 [173.71419 ]
 [179.60085 ]
 [160.14088 ]
 [171.96278 ]
 [174.67078 ]
 [163.77795 ]
 [155.04634 ]
 [193.55226 ]]
1840 Cost: 22.170471 
Prediction:
 [[152.13483 ]
 [187.12442 ]
 [182.20612 ]
 [197.79146 ]
 [144.35541 ]
 [106.026535]
 [145.96852 ]
 [105.1483  ]
 [175.1336  ]
 [161.23714 ]
 [142.57097 ]
 [142.24664 ]
 [188.95811 ]
 [158.3087  ]
 [147.21419 ]
 [188.88759 ]
 [152.88048 ]
 [173.73409 ]
 [179.58977 ]
 [160.13249 ]
 [171.9747  ]
 [174.67293 ]
 [163.78763 ]
 [155.02858 ]
 [193.54451 ]]
1850 Cost: 22.075449 
Prediction:
 [[152.1331 ]
 [187.11958]
 [182.20222]
 [197.7939 ]
 [144.34554]
 [106.02921]
 [145.981  ]
 [105.17258]
 [175.13658]
 [161.25435]
 [142.57533]
 [142.2523 ]
 [188.94722]
 [158.28993]
 [147.22707

In [18]:
# Ask my score
print("Your score will be ", sess.run(hypothesis, 
                                      feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[192.01503]]
Other scores will be  [[150.51588]
 [181.87569]]
