In [1]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [2]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [6]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [7]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  107289.36 
Prediction:
 [[-135.32027]
 [-167.32693]
 [-162.56483]
 [-177.32088]
 [-128.26009]]
10 Cost:  8.833921 
Prediction:
 [[154.41501]
 [180.93346]
 [180.57158]
 [196.3471 ]
 [137.37903]]
20 Cost:  7.8105087 
Prediction:
 [[155.281  ]
 [181.99448]
 [181.60654]
 [197.47522]
 [138.19249]]
30 Cost:  7.769441 
Prediction:
 [[155.27301]
 [182.00497]
 [181.60645]
 [197.47614]
 [138.20464]]
40 Cost:  7.7286043 
Prediction:
 [[155.2624 ]
 [182.01228]
 [181.60323]
 [197.47368]
 [138.21434]]
50 Cost:  7.688005 
Prediction:
 [[155.25183]
 [182.01956]
 [181.6    ]
 [197.47119]
 [138.224  ]]
60 Cost:  7.647607 
Prediction:
 [[155.24126]
 [182.02681]
 [181.59679]
 [197.46872]
 [138.23363]]
70 Cost:  7.607442 
Prediction:
 [[155.23074]
 [182.03403]
 [181.59357]
 [197.46626]
 [138.24326]]
80 Cost:  7.567487 
Prediction:
 [[155.22023]
 [182.04124]
 [181.59036]
 [197.4638 ]
 [138.25282]]
90 Cost:  7.5277543 
Prediction:
 [[155.20976]
 [182.04843]
 [181.58719]
 [197.46135]
 [138.26239]]
10

960 Cost:  4.7777886 
Prediction:
 [[154.3999 ]
 [182.60489]
 [181.34062]
 [197.27057]
 [139.00313]]
970 Cost:  4.753093 
Prediction:
 [[154.39166]
 [182.61057]
 [181.33812]
 [197.26863]
 [139.01068]]
980 Cost:  4.728551 
Prediction:
 [[154.38344]
 [182.6162 ]
 [181.3356 ]
 [197.2667 ]
 [139.0182 ]]
990 Cost:  4.7041225 
Prediction:
 [[154.37524]
 [182.62183]
 [181.33311]
 [197.26472]
 [139.02571]]
1000 Cost:  4.6798687 
Prediction:
 [[154.3671 ]
 [182.62744]
 [181.33066]
 [197.26279]
 [139.0332 ]]
1010 Cost:  4.6556892 
Prediction:
 [[154.35895]
 [182.63306]
 [181.32817]
 [197.26086]
 [139.04068]]
1020 Cost:  4.6316633 
Prediction:
 [[154.35081]
 [182.63864]
 [181.3257 ]
 [197.25894]
 [139.04813]]
1030 Cost:  4.607763 
Prediction:
 [[154.34271]
 [182.64421]
 [181.32323]
 [197.25702]
 [139.05556]]
1040 Cost:  4.5840116 
Prediction:
 [[154.33464]
 [182.64977]
 [181.32079]
 [197.25511]
 [139.06297]]
1050 Cost:  4.5603848 
Prediction:
 [[154.32657]
 [182.6553 ]
 [181.31833]
 [197.2532 ]
 

1810 Cost:  3.0915012 
Prediction:
 [[153.77422]
 [183.035  ]
 [181.1504 ]
 [197.12114]
 [139.57759]]
1820 Cost:  3.075936 
Prediction:
 [[153.7677 ]
 [183.03949]
 [181.14844]
 [197.11957]
 [139.5836 ]]
1830 Cost:  3.0604315 
Prediction:
 [[153.7612 ]
 [183.04398]
 [181.14645]
 [197.118  ]
 [139.5896 ]]
1840 Cost:  3.045016 
Prediction:
 [[153.7547 ]
 [183.04845]
 [181.14449]
 [197.11646]
 [139.59558]]
1850 Cost:  3.0296848 
Prediction:
 [[153.74821]
 [183.05289]
 [181.14253]
 [197.11488]
 [139.60155]]
1860 Cost:  3.0144405 
Prediction:
 [[153.74176]
 [183.05734]
 [181.14056]
 [197.11334]
 [139.60748]]
1870 Cost:  2.9992645 
Prediction:
 [[153.73532]
 [183.06177]
 [181.13861]
 [197.11177]
 [139.61342]]
1880 Cost:  2.984188 
Prediction:
 [[153.7289 ]
 [183.06618]
 [181.13664]
 [197.11023]
 [139.61932]]
1890 Cost:  2.9691648 
Prediction:
 [[153.72249]
 [183.0706 ]
 [181.13472]
 [197.10867]
 [139.62523]]
1900 Cost:  2.9542408 
Prediction:
 [[153.71611]
 [183.075  ]
 [181.13277]
 [197.1071